# Configuración de SonarCloud/SonarQube
sonar.organization=kbrayangarcia
sonar.projectKey=KBrayanGarcia_storybook-components
sonar.projectName=storybook-components

# Rutas de código fuente y pruebas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx

# Exclusiones
sonar.exclusions=node_modules/**,dist/**,coverage/**,**/*.stories.tsx,**/*.stories.ts,.storybook/**,vite.config.ts,.github/**
sonar.coverage.exclusions=node_modules/**,dist/**,coverage/**,**/*.stories.tsx,**/*.stories.ts,.storybook/**,vite.config.ts,.github/**,sonar-project.properties

# Ruta del reporte de cobertura generado por Vitest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificación del código fuente
sonar.sourceEncoding=UTF-8
