name: CI

on:
  push:
    branches-ignore:
      - main  # main lo maneja sonar.yml
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/_tests.yml
